config/routes.rb
Omrails::Application.routes.draw do
  get "users/show"

  resources :pins

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  get 'sessions' => 'pins#sessions'

 get 'about' => 'pages#about'

 root :to => 'pins#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :location, :SurfConditions, :SizeOfWaves, :NumberOfWaves, 
                  :date, :SessionSurfScore, :OverallSurfScore, 
                  :image, :image_remote_url, :surfdate, :SurfConditionRating, :sessiontime,
                  :NumberOfSetWaves

  validates :description, presence: true, :length => { :minimum => 3 }
  validates :location, presence: true, :length => { :minimum => 2 }
  validates :SurfConditions, presence: true, :length => { :minimum => 3}
  validates :SizeOfWaves, presence: true
  validates :NumberOfWaves, presence: true
  validates :surfdate, presence: true
  validates :user_id, presence: true

  #validates :sessiontime, presence: true

  validates :SurfConditionRating, presence: true
  validates :NumberOfSetWaves, presence: true

  validates_attachment :image, presence: true,
  								content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
  								size: { less_than: 5.megabytes }

# CREATING A SUM FOR NUMBEROFWAVES
  


# values = NumberOfWaves.sum(:value, :group => :Total_NumberOfWaves)

# values.each do |Total_NumberOfWaves, value|
#   aggregate_NumberOfWaves = NumberOfWaves.new(:Total_NumberOfWaves => Total_NumberOfWaves, :value => value, :resource_id => 3)
#   @aggregates_NumberOfWaves.push(aggregate_NumberOfWaves)
# end




  belongs_to :user
  has_attached_file :image, styles: { medium: "520x440>", :thumb => "167x147>" }

  def image_remote_url=(url_value)
  	self.image = URI.parse(url_value) unless url_value.blank?
  	super
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable, -> activate when mailer is set up and we're off of localhost
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body


  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def sessions
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
before_filter :authenticate_user!, except: [:index]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(20)

    @date = params[:month] ? Date.parse(params[:month]) : Date.today

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
      format.js
    end
  end

  # GET /pins
  # GET /pins.json
    def sessions
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(20)

    @date = params[:month] ? Date.parse(params[:month]) : Date.today

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
      format.js
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = Pin.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

	   @pins = @user.pins.page(params[:page]).per_page(20)

	  
	  respond_to do |format|
      	format.html # show.html.erb
      	format.json { render json: @pins }
      	format.js
	     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/_footer.html.erb
<div class="container">
	<div class="footer">
		<div class="navbar navbar-fixed-bottom">
			<small>
				<div class="pull-right">
				By <%= link_to "Marco Morawec", "http://www.marcomorawec.com" %>
				</div>
			</small>
		</div>
	</div>
</div>

<% if current_page?('/') && !user_signed_in? %>
	<script>
		$.backstretch([
		"<%= asset_path 'bck1.jpg' %>",
		"<%= asset_path 'bck2.png' %>",
		"<%= asset_path 'bck3.jpg' %>",
		], {duration: 4000, fade: 750});
	</script>
<% else %>
	<script>
		$.backstretch("<%= asset_path 'homebackground.jpg' %>")
	</script>
<% end %>

app/views/layouts/_header.html.erb
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
	    <div class="container">
	     
		    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
		    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
		    </a>
		     
		    <!-- Be sure to leave the brand out there if you want it shown -->
		    
		    <%= link_to image_tag('logonav_small.png'), root_path, class: "pull-left img-logo"  %>
		    <%= link_to "SurfScore", root_path, class: "brand" %>

		    <!-- Everything you want hidden at 940px or less, place within here -->
		    <div class="nav-collapse collapse">
		    	<ul class="nav">
		    		<li><%= link_to "Home", root_path %></li>
		    		<li><%= link_to "About", about_path %></li>
		    	<% if user_signed_in? %>
		    		<li><%= link_to "My Sessions", sessions_path %></li>
		    	<% end %>
		    	</ul>
		    	<ul class="nav pull-right">
		    		<% if user_signed_in? %>
		    			<li><%= link_to "Add +", new_pin_path %></li>
		    			<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
		    			<li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
		    		<% else %> 
		    			<li><%= link_to "login", new_user_session_path %></li>
		    		<% end %>
		    	</ul>
		    <!-- .nav, .navbar-search, .navbar-form, etc -->
		    </div>
	     
	    </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>SurfScore</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <!--<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" %> -->
	  <%= csrf_meta_tags %>
	  	<!--[if lt IE 8]>
			<%= stylesheet_link_tag "font-awesome-ie7.min.css", media: "all" %>
		<![endif]-->
	</head>
	<body>
		<div class="container">
			<%=render 'layouts/header' %>

				<% flash.each do |name, msg| %>
					<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
				<% end %>
					<%= yield %>
			<%=render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/_dashboard.html.erb
<% if user_signed_in? %>
	<div class="container">
		<div class="hero-unit frosty">
			<h1 class="custom-h1">
				<% if current_user == @user %>
					<% @user.name %>
				<% end %>
			</h1>
				<h1 class="custom-h1">Lifetime Surfing Sessions</h1>
					<div class="row">
							<div class="span4">
									<h2 class="custom-h2">Total Waves</h2>
									<h3  class="dashboard-score">
									<!-- Need to sum for each user seperately -->
										<%= Pin.sum(:NumberOfWaves) %>							
									</h3>
							</div>
							<div class="span4">
									<h2 class="custom-h2">Total Watertime</h2>
									<h3  class="dashboard-score">
										512
									</h3>
							</div>
							<div class="span4">
									<h2 class="custom-h2">Total Set Waves</h2>
									<h3 class="dashboard-score">
										<%= Pin.sum(:NumberOfSetWaves) %>							
									</h3>
							</div>
						</div>
						<div class="row">
							<div class="span4">
									<h2 class="custom-h2">Waves per Session</h2>
									<h3  class="dashboard-score">
										<%= Pin.average(:NumberOfWaves).round %>							
									</h3>
							</div>
							<div class="span4">
									<h2 class="custom-h2">Average Watertime</h2>
									<h3  class="dashboard-score">512</h3>
							</div>
							<div class="span4">
									<h2 class="custom-h2">Set Waves per Session</h2>
									<h3  class="dashboard-score">
										<%= Pin.average(:NumberOfSetWaves).round %>							
									</h3>
							</div>
						</div>																
					</div>
		</div>
	</div>

<% end %>

app/views/pages/_home.html.erb
<div class="container">
	<% if !user_signed_in? %>
		<div class="span5">		
			<%= render 'devise/registrations/new' %>
		</div>
	<% end %>
</div>

app/views/pages/about.html.erb
<div class="container">

	<h1>About</h1>

	<p>

		<%= link_to "Surfscore", "http://surfscore.me" %>
		tracks your performance for all action sports.
	</P>
</div>

app/views/pages/home.html.erb
	<div class="container">
		<% if user_signed_in? %>
			<div class="span5 offset3">
				<div class="hero-unit frosty">
					<h2>Welcome back!</h2>
					<h3>Let's get you shredding</h>
				</div>
			</div>
		<% else %>
			<div class="span5 offset3">
				<div class="hero-unit frosty">
					<h2>Improve your Surfing</h2>
						<p>
							Track Each Wave. Surf Better!
						</p>


						<p>
							<%= link_to "Sign up Now!", new_user_registration_path, class: "btn btn-success" %>
						</p>
				</div>
			</div>
		<% end %>
	</div>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

    <%= f.input :image, label: "Upload a Session Image" %>
    <%= f.input :image_remote_url, label: "Paste the Image URL" %>

    <%= f.input :SurfConditionRating, collection: 1..5, label: "Rate your Session (1=bad, 5=epic)?" %>

    <%= f.input :NumberOfWaves, label: "How many waves did you catch?" %>
    <%= f.input :NumberOfSetWaves, label: "How many Set-Waves?" %>


    <%= f.input :surfdate, label: "When did you surf?"  %>


    <%= f.input :location, label: "Where did you surf"  %>

    <%= f.input :description, label: "Two Word Session Sum Up" %>

  <div class="pull-right">
    <%= f.button :submit, class: "btn btn-large btn-danger", value: "Make the Session" %> |
    <%= link_to 'Show', @pin %> |
    <%= link_to 'Back', pins_path %>

<!-- Trying to get the Javascript for the slider to work -->
<script type="text/javascript">
  $('.slider').slider(options)
</script>

  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
	<div class="img-wrap">
		<%= link_to image_tag(pin.image(:medium)), pin_path(pin) %>
		<div class="img-overlay image-description">
			<%= pin.description %>
		</div>
	</div>
	<% if (pin.NumberOfWaves && pin.SurfConditions) %>
		<h4 class="custom-h4">
			<%= pin.NumberOfWaves %> Wave Count || <%= pin.SurfConditions %>
		</h4>
	<% end %> 	
	<p>
		Posted by <%= link_to pin.user.name, pin.user %>
	</p>

	<%= link_to 'Show', pin %>

	<% if current_user == pin.user %>
	    <%= link_to 'Edit', edit_pin_path(pin) %>
	    <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
</div>

app/views/pins/edit.html.erb
<div class="span7 offset1 frosty">

	<h1>Adjust your Surf Session</h1>

	<br></br>
	<%= render 'form' %> 

</div>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<% if user_signed_in? %>
	<div class="hero-unit frosty">
		<h1 class="custom-h1">Top Surf Sessions</h1>
	</div>
<!-- Show the pins -->


	<div id="pins" >
	  <%= render @pins %>
	</div>
	  <!-- show the pagination -->
	<div class="">
	  <%= will_paginate @pins %>
	</div>
<% end %>
<!-- End of pins -->

app/views/pins/index.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
  $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/pins/new.html.erb
<div class="span8 offset1 frosty">

	<h1 class="custom-h1">Make a Surf Session</h1>
	<br></br>

	<%= render 'form' %>

</div>

app/views/pins/sessions.html.erb
<!-- Show each user only his own Sessions in the Dashboard and the Calendar -->

<!-- Start of Dashboard -->

<%= render 'pages/dashboard' %>

<!-- End of Dashboard -->


<!-- adding the calendar view -->

	<% if user_signed_in? %>
		<div class="container">
		  	<h2 id="month">
			    <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m") %>
			    <%=h @date.strftime("%B %Y") %>
			    <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m") %>
			</h2>
			<div id="calendar">
				<%= calendar_for(@tasks) do |t| %>
					<%= t.head('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday') %>
					<%= t.day do |day, tasks, pins| %>
				    	<%= day.day %>
							<%= link_to  do %>
							<!-- add on hover class here -->
							  <i class="icon-edi icon-2 pull-right"></i>
							<% end %>
							<%= link_to new_pin_path do %>
							<!-- add on hover class here -->
							  <i class="icon-plus-sig icon-2 pull-right"></i>
							<% end %>
					    <% tasks.each do |task| %>
					      <%= h(task.name) %>
				    	<% end %>
				      	<ul>
						    <% for pin in @pins %>
								<% if pin.surfdate == day %>
							
									<li>
										<div class="box-calendar">
											<div class="img-wrap">
												<%= link_to image_tag(pin.image(:thumb)), pin %>
												<div class="img-overlay image-description">
													<%= pin.description %>
												</div>
											</div>
										</div>
									</li>
										<h4 class="custom-h4">
										<%= pin.NumberOfWaves %> Waves || <%= pin.SurfConditions %>
										</h4> 				        
									<% end %>
						    <% end %>
					    </ul>		  
					<% end %>
				<% end %>
			</div>
	<% end %>
<!-- End of Calendar View -->

app/views/pins/show.html.erb
<div class="row">
	<div class="span11 offset1">
		<div class="frosty">
			<div class="span11">
				<div class= "row">
					<div class="span1">
						<div class="circle-overall">
							<p class="radical-score">9.8</p>
						</div>
					</div>
						<div class="span4">
							<h1 class="custom-h1"><%= @pin.user.name %></h1>
						</div>
					<div class="span6 image-description">
			  			<h1 class="custom-h1">Session Stats</h1>
					</div>
				</div>
			</div>
			<div class="span11">
				<ul class="nav nav-list">
					<li class="divider"></li>
				</ul>
			</div>
			<div class="row">
				<div class="span7">
				  	<%= image_tag @pin.image %>
					</p>
					<p>
				  	<h3 class="custom-h3"><%= @pin.description %> by <%= @pin.user.name %> - <%= @pin.location %></h3>
					</p>
					<% if current_user == @pin.user %>
						<%= link_to 'Edit', edit_pin_path(@pin) %> |
					<% end %>
					<%= link_to 'Back', pins_path %>
				</div>
				<div class="span4">
					<div class="row">
						<div class="span1">
							<div class="circle-sessions">
								<p class="radical-score"><%= 7.3 %></p>
							</div>
						</div>
						<div class="span3">
							<h2 class="custom-h2">Session Score</h2>
						</div>
					</div>
					<h2 class="custom-h2">How big was it?</h2>
						<h3 class="custom-h3">The waves were <%= @pin.SizeOfWaves %> Feet</h3>
					<h2 class="custom-h2">Surf Conditions?</h2>
						<h3 class="custom-h3"><%= @pin.SurfConditions %></h3>
					<h2 class="custom-h2">How many waves?</h2>
						<h3 class="custom-h3">I got <%= @pin.NumberOfWaves %> waves!</h3>
					<h2 class="custom-h2">When was the session?</h2>
						<h3 class="custom-h3">I surfed on <%= @pin.surfdate %> </h3>
				</div>
			</div>
		</div>	
	</div>	
</div>

app/views/pins/show.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
  $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/users/show.html.erb
<h1>Surf Action from <%= @user.name %>!</h1>

<div id="pins" >
  <%= render @pins %>
</div>
  <!-- show the pagination -->
  <div class="">
  <%= will_paginate @pins %>
</div>